#include <stdio.h>

 int main ()
 {
 int TIPOPIZZA, INGREDIENTEV, INGREDIENTESNV;
 printf ("ELIJA QUE TIPO DE PIZZA DESEA COMPRAR:\n 1. SI QUIERE UNA PIZZA VEGETARIANA\n 2. SI QUIERES UNA PIZZA NO VEGETARIANA\n ");
 scanf ("%d", &TIPOPIZZA);

 if (TIPOPIZZA==1){
 printf ("ELIJA EL INGREDIENTE QUE LLEVARA SU PIZZA:\n 1. PIMIENTO\n 2. TOFU\n");
 scanf ("%d", &INGREDIENTEV);
 if (INGREDIENTEV==1){
            printf ("GRACIAS POR SU COMPRA, SU PIZZA ES VEGETARIANA Y LOS INGREDIENTES QUE LLEVA SON MOZZARELLA, TOAMTE Y PIMIENTO\n");
 } else {
            printf ("GRACIAS POR SU COMPRA, SU PIZZA ES VEGETARIANA Y LOS INGREDIENTES QUE LLEVA SON MOZZARELLA, TOAMTE Y TOFU\n");
            }
 }
 if (TIPOPIZZA==2){
     printf ("ELIJA EL INGREDIENTE QUE LLEVARA SU PIZZA:\n 1. PEPERONI\n 2. JAMON\n 3. SALMON\n");
 scanf ("%d", &INGREDIENTESNV);
 if (INGREDIENTESNV==1){
            printf ("GRACIAS POR SU COMPRA, SU PIZZA ES NO VEGETARIANA Y LOS INGREDIENTES QUE LLEVA SON MOZZARELLA, TOAMTE Y PEPERONI");
 }  else if (INGREDIENTESNV==2) {
            printf ("GRACIAS POR SU COMPRA, SU PIZZA ES NO VEGETARIANA Y LOS INGREDIENTES QUE LLEVA SON MOZZARELLA, TOAMTE Y JAMON");
            }
            else{
                 printf ("GRACIAS POR SU COMPRA, SU PIZZA ES NO VEGETARIANA Y LOS INGREDIENTES QUE LLEVA SON MOZZARELLA, TOAMTE Y SALMON");
            }

 }

 return 0;
 }
